version[1.5]: released

diff --git a/yt_download b/yt_download
--- a/yt_download
+++ b/yt_download
@@ -36,6 +36,15 @@
 #	1.4:
 #		- Added support to download audio
 #		  from a playlist.
+#
+#	1.5:
+#	  - Visual feedback to the download
+#	  - Testing dependencies to run the script
+#	  Changed:
+#	    - Output directory where the command
+#	      is called
+#
+#	    - Output directory isn't tested anymore
 #============================================|
 
 # VERIFICATIONS
@@ -44,19 +53,22 @@
 [[ "$UID" -eq '0' ]] && { echo 'Do not run as root' ; exit 1 ; }
 
 # test if the necessary module exist
-[[ $( type -p yt-dlp ) ]] || { echo 'yt-dlp not found.' ; exit 1 ; }
+[[ $( type -p yt-dlp ) ]] || { echo 'yt-dlp not found' ; exit 1 ; }
 
 # Test internet conection
 [[ $( ping -c1 8.8.8.8 ) ]] || { echo 'You need internet conection to run the script' ; exit 1 ; }
 
-# test if the directory exists
-[[ ! -e "$HOME/Downloads/Youtube_Download" ]] \
-&& { echo 'created directory ~Downloads/Youtube_Download' ; mkdir -p "$HOME/Downloads/Youtube_Download" ; }
+# test if the dependencies are avaiable
+# mutagen
+[[ $( pip list | grep mutagen | tr -s " " | cut -d " " -f 1 ) = "mutagen" ]] || { echo 'python-mutagen was not found, please install the dependency' ; exit 1 ; }
+
+# ffmpeg
+[[ $(type -P ffmpeg) ]] || { echo 'ffmpeg was not found, please install the dependency' ; exit 1 ; }
 
 #============================================| GLOBAL VARIABLES
 
-version='1.4'
-output_directory="$HOME/Downloads/Youtube_Download/%(title)s.%(ext)s"
+version='1.5'
+output_directory="./%(title)s.%(ext)s"
 
 #============================================| FUNCTIONS
 
@@ -90,16 +102,11 @@ function download_audio() {
 	local youtube_regex='^(https?\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$'
 	[[ $1 =~ $youtube_regex ]] || { echo 'It is not a valid link, please provide a https://youtube.com/...' ; exit 1 ; }
 
+  local title="Downloading audio..."
+  [[ "$2" = "yes" ]] && title="Downloading playlist..."
 
-	echo 'Starting the download...'
-	if yt-dlp -x -f bestaudio -o "$output_directory" --embed-thumbnail --"${2}"-playlist "$1" >&- 2>&- ; then
-		echo 'Download was successful, saved in:'
-		echo "$HOME/Downloads/Youtube_Download"
-		exit 0
-	else
-		echo $'\E[31;1mAn error has occurred.\E[0m\nUse -h or --help to know more.'
-		exit 1
-	fi
+	gum spin --spinner dot --title "${title}" -- yt-dlp -x -f bestaudio -o "$output_directory" --embed-thumbnail --"${2}"-playlist "$1" && { echo 'Download completed' ; exit 0 ; } || { echo 'Error' ; exit 1 ; }
+
 }
 
 #============================================|START THE PROGRAM
